[package]
name = "os"
version = "0.1.0"
authors = ["csy <505007945@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
